import openstack
import datetime
import streamlit as st
import re

# ---------------------------------------------------------
# WEB PAGE CONFIGURATION
# ---------------------------------------------------------
st.set_page_config(page_title="OpenStack Backup Manager", page_icon="☁️", layout="centered")

st.title("☁️ Cinder Backup Manager")
st.markdown("Welcome to the automated backup management tool for **OpenStack Cinder** volumes.")
st.divider()

# ---------------------------------------------------------
# CONNECTION TO OPENSTACK API
# ---------------------------------------------------------
@st.cache_resource
def connect_to_cloud():
    try:
        return openstack.connect()
    except Exception as e:
        return None

conn = connect_to_cloud()

if not conn:
    st.error("❌ Failed to connect to the OpenStack API. Check your credentials (openrc).")
else:
    st.success("✅ Successfully connected to the OpenStack API.")
    
    # Create two tabs to separate creation from cleanup
    tab1, tab2 = st.tabs(["💾 Create Backups", "🧹 Automatic Cleanup"])
    
    # --- TAB 1: CREATE BACKUPS ---
    with tab1:
        st.subheader("Analyze and Create Backups")
        st.info("Backups will only be created for volumes attached to an instance ('in-use').")
        
        if st.button("▶️ Start Backup System", type="primary"):
            with st.spinner('Connecting to Cinder to retrieve volumes...'):
                volumes = list(conn.block_storage.volumes())
                
            st.write(f"Found **{len(volumes)} volumes** in the cloud.")
            
            progress_bar = st.progress(0)
            
            for index, volume in enumerate(volumes):
                with st.expander(f"Volume: {volume.name} (Size: {volume.size}GB | Status: {volume.status})", expanded=True):
                    
                    if volume.status == 'in-use':
                        current_date = datetime.datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
                        backup_name = f"auto-backup-{volume.name}-{current_date}"
                        
                        st.write(f"🔄 Volume is in use. Creating Snapshot: `{backup_name}`...")
                        
                        conn.block_storage.create_snapshot(
                            volume_id=volume.id,
                            name=backup_name,
                            description="Automated backup generated by Python GUI",
                            is_forced=True
                        )
                        st.success("✔️ Backup command sent successfully.")
                    else:
                        st.warning("⚠️ Volume is not attached to any instance. Skipping.")
                
                progress_bar.progress((index + 1) / len(volumes))
                
            st.balloons()
            st.success("=== Backup Process Finished ===")

    # --- TAB 2: CLEANUP OF OLD BACKUPS ---
    with tab2:
        st.subheader("Clean Up Obsolete Backups")
        
        # Graphical slider to select retention period
        retention_days = st.slider("How many days do you want to keep the backups?", min_value=1, max_value=14, value=3)
        max_snapshots = st.number_input("Max snapshots to keep per volume", min_value=1, value=3)
        
        if st.button("🗑️ Start Cleanup of Old Backups"):
            with st.spinner('Analyzing old snapshots...'):
                snapshots = list(conn.block_storage.snapshots())
                limit_date = datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(days=retention_days)
                
                deleted_count = 0
                
                for snap in snapshots:
                    if snap.name and snap.name.startswith("auto-backup"):
                        try:
                            creation_date = None
                            
                            # Method 1: Try to parse date from OpenStack metadata
                            if getattr(snap, 'created_at', None):
                                try:
                                    date_str = snap.created_at.replace('Z', '+00:00')
                                    creation_date = datetime.datetime.fromisoformat(date_str)
                                except ValueError:
                                    pass
                            
                            # Method 2: Bulletproof fallback - Parse date directly from snapshot name
                            if not creation_date:
                                match = re.search(r'(\d{4}-\d{2}-\d{2}_\d{2}-\d{2}(?:-\d{2})?)$', snap.name)
                                if match:
                                    date_str = match.group(1)
                                    # Handle both old format (without seconds) and new format
                                    if len(date_str) == 16:
                                        creation_date = datetime.datetime.strptime(date_str, '%Y-%m-%d_%H-%M')
                                    else:
                                        creation_date = datetime.datetime.strptime(date_str, '%Y-%m-%d_%H-%M-%S')

                            # Execution: Assign UTC and compare dates safely
                            if creation_date:
                                if creation_date.tzinfo is None:
                                    creation_date = creation_date.replace(tzinfo=datetime.timezone.utc)
                                
                                if creation_date < limit_date:
                                    st.error(f"🗑️ Deleting old backup: {snap.name}")
                                    conn.block_storage.delete_snapshot(snap.id)
                                    deleted_count += 1
                                else:
                                    st.write(f"✅ Keeping recent backup: {snap.name}")
                            else:
                                st.warning(f"⚠️ Could not extract date from {snap.name}")
                                
                        except Exception as e:
                            # If it fails, show the exact reason
                            st.write(f"❌ Error processing {snap.name}. Detail: {str(e)}")
                
                st.success(f"Cleanup finished. Deleted **{deleted_count}** obsolete backups.")