import openstack
import datetime
import streamlit as st

# ---------------------------------------------------------
# WEB PAGE CONFIGURATION
# ---------------------------------------------------------
st.set_page_config(page_title="OpenStack Backup Manager", page_icon="☁️", layout="centered")

st.title("☁️ Cinder Backup Manager")
st.markdown("Welcome to the automated backup management tool for **OpenStack Cinder** volumes.")
st.divider()

# ---------------------------------------------------------
# CONNECTION TO OPENSTACK API
# ---------------------------------------------------------
@st.cache_resource
def connect_to_cloud():
    try:
        return openstack.connect()
    except Exception as e:
        return None

conn = connect_to_cloud()

if not conn:
    st.error("❌ Failed to connect to the OpenStack API. Check your credentials (openrc).")
else:
    st.success("✅ Successfully connected to the OpenStack API.")
    
    # Create two tabs to separate creation from cleanup
    tab1, tab2 = st.tabs(["💾 Create Backups", "🧹 Automatic Cleanup"])
    
    # --- TAB 1: CREATE BACKUPS ---
    with tab1:
        st.subheader("Analyze and Create Backups")
        st.info("Backups will only be created for volumes attached to an instance ('in-use').")
        
        if st.button("▶️ Start Backup System", type="primary"):
            with st.spinner('Connecting to Cinder to retrieve volumes...'):
                volumes = list(conn.block_storage.volumes())
                
            st.write(f"Found **{len(volumes)} volumes** in the cloud.")
            
            # Create a progress bar to make it more visual
            progress_bar = st.progress(0)
            
            for index, volume in enumerate(volumes):
                with st.expander(f"Volume: {volume.name} (Size: {volume.size}GB | Status: {volume.status})", expanded=True):
                    
                    if volume.status == 'in-use':
                        current_date = datetime.datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
                        backup_name = f"auto-backup-{volume.name}-{current_date}"
                        
                        st.write(f"🔄 Volume is in use. Creating Snapshot: `{backup_name}`...")
                        
                        # Actual API code
                        conn.block_storage.create_snapshot(
                            volume_id=volume.id,
                            name=backup_name,
                            description="Automated backup generated by Python GUI",
                            is_forced=True
                        )
                        st.success("✔️ Backup command sent successfully.")
                    else:
                        st.warning("⚠️ Volume is not attached to any instance. Skipping.")
                
                # Update the progress bar
                progress_bar.progress((index + 1) / len(volumes))
                
            st.balloons() # Final success animation!
            st.success("=== Backup Process Finished ===")

    # --- TAB 2: CLEANUP OF OLD BACKUPS ---
    with tab2:
        st.subheader("Clean Up Obsolete Backups")
        
        # A graphical slider so the professor can see you can parameterize it
        retention_days = st.slider("How many days do you want to keep the backups?", min_value=1, max_value=14, value=3)
        
        if st.button("🗑️ Start Cleanup of Old Backups"):
            with st.spinner('Analyzing old snapshots...'):
                snapshots = list(conn.block_storage.snapshots())
                limit_date = datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(days=retention_days)
                
                deleted_count = 0
                
                for snap in snapshots:
                    if snap.name and snap.name.startswith("auto-backup"):
                        try:
                            creation_date = datetime.datetime.fromisoformat(snap.created_at.replace('Z', '+00:00'))
                            
                            if creation_date < limit_date:
                                st.error(f"🗑️ Deleting old backup: {snap.name} (Created: {creation_date.strftime('%Y-%m-%d')})")
                                conn.block_storage.delete_snapshot(snap.id)
                                deleted_count += 1
                            else:
                                st.write(f"✅ Keeping recent backup: {snap.name}")
                        except Exception as e:
                            st.write(f"❌ Could not verify the date for {snap.name}.")
                
                st.success(f"Cleanup finished. Deleted **{deleted_count}** obsolete backups.")