import openstack
import datetime

# 1. Connect to the cloud API
print("Connecting to OpenStack API...\n")
conn = openstack.connect()

print("=== Starting Backup System (Cinder API) ===")

# Request the list of all volumes from Cinder
volumes = list(conn.block_storage.volumes())
print(f"Found {len(volumes)} volumes in the cloud.\n")

for volume in volumes:
    print(f"Analyzing volume: {volume.name} (Size: {volume.size}GB, Status: {volume.status})")
    
    # Core Logic: Only backup volumes that are attached to an instance ('in-use')
    if volume.status == 'in-use':
        # Generate a unique name with the current date and time
        current_date = datetime.datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
        backup_name = f"auto-backup-{volume.name}-{current_date}"
        
        print(f" -> Volume is in use. Calling API to create Snapshot: {backup_name}...")
        
        # Send the command to Cinder to create the backup
        conn.block_storage.create_snapshot(
            volume_id=volume.id,
            name=backup_name,
            description="Automated backup generated by Python script",
            is_forced=True
        )
        print(" -> [OK] Backup command sent successfully.")
    else:
        print(" -> Volume is not attached to any instance. Skipping.")

print("\n=== Backup process finished ===\n")

# PART 2: CLEANUP OF OLD BACKUPS
print("=== Starting Cleanup of Old Backups ===")

# Request all snapshots from Cinder
snapshots = list(conn.block_storage.snapshots())
retention_days = 3  # Keep backups for 3 days
limit_date = datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(days=retention_days)

deleted_count = 0

for snap in snapshots:
    # Only process snapshots created by this script
    if snap.name and snap.name.startswith("auto-backup"):
        # Convert OpenStack creation date to a Python datetime object
        try:
            # Format handling for OpenStack date string
            creation_date = datetime.datetime.fromisoformat(snap.created_at.replace('Z', '+00:00'))
            
            if creation_date < limit_date:
                print(f" -> Deleting old backup: {snap.name} (Created: {creation_date.strftime('%Y-%m-%d')})")
                conn.block_storage.delete_snapshot(snap.id)
                deleted_count += 1
            else:
                print(f" -> Keeping recent backup: {snap.name}")
        except Exception as e:
            print(f" -> Could not verify date for {snap.name}. Error: {e}")

print(f"\n=== Cleanup finished. Deleted {deleted_count} old backups ===")