import openstack
import datetime

# 1. Connect to the cloud API
print("Connecting to OpenStack API...\n")
conn = openstack.connect()

print("=== Starting Backup System (Cinder API) ===")

# Request the list of all volumes from Cinder
volumes = list(conn.block_storage.volumes())
print(f"Found {len(volumes)} volumes in the cloud.\n")

for volume in volumes:
    print(f"Analyzing volume: {volume.name} (Size: {volume.size}GB, Status: {volume.status})")
    
    # Core Logic: Only backup volumes that are attached to an instance ('in-use')
    if volume.status == 'in-use':
        # Generate a unique name with the current date and time
        current_date = datetime.datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
        backup_name = f"auto-backup-{volume.name}-{current_date}"
        
        print(f" -> Volume is in use. Calling API to create Snapshot: {backup_name}...")
        
        # Send the command to Cinder to create the backup
        conn.block_storage.create_snapshot(
            volume_id=volume.id,
            name=backup_name,
            description="Automated backup generated by Python script",
            is_forced=True
        )
        print(" -> [OK] Backup command sent successfully.")
    else:
        print(" -> Volume is not attached to any instance. Skipping.")

print("\n=== Backup process finished ===\n")

# --- TAB 2: CLEANUP OF OLD BACKUPS ---
    with tab2:
        st.subheader("Clean Up Obsolete Backups")
        
        # A graphical slider to parameterize the retention policy
        retention_days = st.slider("How many days do you want to keep the backups?", min_value=1, max_value=14, value=3)
        
        if st.button("🗑️ Start Cleanup of Old Backups"):
            with st.spinner('Analyzing old snapshots...'):
                snapshots = list(conn.block_storage.snapshots())
                limit_date = datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(days=retention_days)
                
                deleted_count = 0
                
                for snap in snapshots:
                    if snap.name and snap.name.startswith("auto-backup"):
                        try:
                            creation_date = None
                            
                            # 1. Primary Method: Try to get the date from OpenStack metadata
                            if getattr(snap, 'created_at', None):
                                date_str = snap.created_at.replace('Z', '+00:00')
                                creation_date = datetime.datetime.fromisoformat(date_str)
                            
                            # 2. Ensure timezone is set to UTC for safe comparison
                            if creation_date and creation_date.tzinfo is None:
                                creation_date = creation_date.replace(tzinfo=datetime.timezone.utc)
                            
                            # 3. Execution: Compare and delete if older than threshold
                            if creation_date:
                                if creation_date < limit_date:
                                    st.error(f"🗑️ Deleting old backup: {snap.name} (Created: {creation_date.strftime('%Y-%m-%d')})")
                                    conn.block_storage.delete_snapshot(snap.id)
                                    deleted_count += 1
                                else:
                                    st.write(f"✅ Keeping recent backup: {snap.name}")
                            else:
                                st.warning(f"⚠️ Skipping {snap.name}: No valid creation date found.")
                                
                        except Exception as e:
                            # Show the exact error message to facilitate debugging
                            st.write(f"❌ Could not verify the date for {snap.name}. Detail: {str(e)}")
                
                st.success(f"Cleanup finished. Deleted **{deleted_count}** obsolete backups.")